export const variantsData = [
  {
    id: "victoria",
    url: "/",
    textColor: "txtColor",
    menu: "/icons/menu.svg",
    close: "/icons/close.svg",
    menuGradient: "dark-to-light",
    menuHeart: "/icons/heart.svg",
    burgerBg: "burger-bg",
    txtGradient: "txt-gradient",
    lightGradient: "lightGradient",
    firstbg: "bgFirstAndSecondBlocks",
    banner: {
      womanPhoto: "/images/hero/hero.webp",
      womanClass: "top-[78px]",
      womanImg: "w-[299px]",
      roseBack: "/images/hero/rose-back.webp",
      roseBgClass: "object-[-97px_0]",
      bannerGradientClass: "top-[406px] bg-[#170101]  w-[521px] h-[783px]",
      roseL: "/images/hero/rose-l.webp",
      roseR: "/images/hero/rose-r.webp",
      bannerTxt: "Сила любви у тебя в руках",
      accentTxt: "Забери своё",
      lastTxt: "Пошаговый ритуал, который может всё изменить",
    },
    txtSection: {
      img: "/images/txtSection/img.png",
      gradient: "bg-[#470808]",
    },
    about: {
      heart: "/images/about/heart.webp",
      roseL: "/images/about/rose-l.png",
      roseR: "/images/about/rose-r.png",
      itemClass: "borderColor bg-dark-to-light",
    },
    successRate: {
      gradient: "bg-[#470808]",
      gradientSecond:
        "radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 61, 0.30) 0%, rgba(51, 5, 10, 0.30) 100%)",
      ellipceImg: "/images/successRate/ellipceImg.webp",
      card: "/images/successRate/card.webp",
      roseR: "/images/successRate/rose-r.png",
      woman: "/images/successRate/woman.webp",
      borderClass: "border-gradient-rounded",
      accentBg: "bg-accent-gradient",
    },
    target: {
      mainImg: "/images/target/img1.webp",
      roseBack: "/images/target/rose-back.webp",
      roseL: "/images/target/rose-l.png",
      roseClass: "object-[-161px_56px]",
      borderColor: "borderColor",
    },
    videoInstruction: {
      bg: "/images/videoInstruction/bg.webp",
      gradient: "bg-[#170101]",
      card: "/images/videoInstruction/card.png",
      roseL: "/images/videoInstruction/rose-l.png",
      roseR: "/images/videoInstruction/rose-r.png",
    },
    reviews: {
      heart: "/images/reviews/heart.webp",
      gradient:
        "radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 61, 0.50) 0%, rgba(51, 5, 10, 0.50) 100%)",
      slideBg: "bg-[#A61F2C]",
      quotes: "/icons/quotes.svg",
      play: "/icons/play.svg",
      prev: "/icons/prev.svg",
      prevClass: "w-[168px] object-[0_1px]",
      next: "/icons/next.svg",
    },
  },
  {
    id: "ayym-qunan",
    url: "/ayym-qunan",
    textColor: "txtColor2",
    menu: "/icons/menu2.svg",
    close: "/icons/close2.svg",
    menuGradient: "dark-to-light-2",
    menuHeart: "/images/heart2.webp",
    burgerBg: "burger-bg-2",
    txtGradient: "txt-gradient-2",
    lightGradient: "lightGradient-2",
    firstbg: "bgFirstAndSecondBlocks-second",
    banner: {
      womanPhoto: "/images/hero-2/hero.webp",
      womanClass: "top-[-1px]",
      womanImg: "w-full",
      roseBack: "/images/hero-2/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#010D17]  w-[662px] h-[832px]",
      roseL: "/images/hero-2/rose-l.png",
      roseR: "/images/hero-2/rose-r.png",
      bannerTxt: "Возвращение любимого",
      accentTxt: "Забери своё",
      lastTxt: "100% проверенная практика, которую используют мастера",
    },
    txtSection: {
      img: "/images/txtSection/img-2.png",
      gradient: "bg-[#39394A]",
    },
    about: {
      heart: "/images/about-2/heart.webp",
      roseL: "/images/about-2/rose-l.png",
      roseR: "/images/about-2/rose-r.png",
      itemClass: "borderColor-2 bg-dark-to-light",
    },
    successRate: {
      gradient: "bg-[#39394A]",
      gradientSecond:
        "radial-gradient(50% 50% at 50% 50%, rgba(39, 79, 255, 0.30) 0%, rgba(5, 14, 51, 0.30) 100%)",
      ellipceImg: "/images/successRate-2/ellipceImg.webp",
      card: "/images/successRate-2/card.webp",
      roseR: "/images/successRate-2/rose-r.png",
      woman: "/images/successRate-2/woman.webp",
      borderClass: "border-gradient-rounded-2",
      accentBg: "bg-accent-gradient-2",
    },
    target: {
      mainImg: "/images/target-2/img1.webp",
      roseBack: "/images/target-2/rose-back.webp",
      roseL: "/images/target-2/rose-l.png",
      borderColor: "borderColor-2",
    },
    videoInstruction: {
      bg: "/images/videoInstruction-2/bg.webp",
      gradient: "bg-[#010D17]",
      card: "/images/videoInstruction-2/card.png",
      roseL: "/images/videoInstruction-2/rose-l.png",
      roseR: "/images/videoInstruction-2/rose-r.png",
    },
    reviews: {
      heart: "/images/reviews/heart-2.svg",
      gradient:
        "radial-gradient(50% 50% at 50% 50%, rgba(39, 68, 255, 0.50) 0%, rgba(5, 10, 51, 0.50) 100%)",
      slideBg: "bg-[#2851B7]",
      quotes: "/icons/quotes-2.svg",
      play: "/icons/play-2.svg",
      prev: "/icons/prev-2.svg",
      prevClass: "w-[153px] object-[0_4px]",
      next: "/icons/next-2.svg",
    },
  },
  {
    id: "anastasia",
    url: "/anastasia",
    textColor: "txtColor3",
    menu: "/icons/menu3.svg",
    close: "/icons/close3.svg",
    menuGradient: "dark-to-light-3",
    menuHeart: "/icons/heart-3.svg",
    burgerBg: "burger-bg-3",
    txtGradient: "txt-gradient-3",
    lightGradient: "lightGradient-3",
    firstbg: "bgFirstAndSecondBlocks-third",
    banner: {
      womanPhoto: "/images/hero-3/hero.webp",
      womanClass: "top-[-1px]",
      womanImg: "w-full",
      roseBack: "/images/hero-3/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#170111]  w-[662px] h-[832px]",
      roseL: "/images/hero-3/rose-l.png",
      roseR: "/images/hero-3/rose-r.png",
      bannerTxt: "Научись притягивать",
      accentTxt: "Ты - наслаждение",
      lastTxt: "Курс для тех, кто хочет раскрыть свою природную магнетичность",
    },
    txtSection: {
      img: "/images/txtSection/img-3.png",
      gradient: "bg-[#4A3945]",
    },
    about: {
      heart: "/images/about-3/heart.webp",
      roseL: "/images/about-3/rose-l.png",
      roseR: "/images/about-3/rose-r.png",
      itemClass: "borderColor-3 bg-dark-to-light",
    },
    successRate: {
      gradient: "bg-[#4A3945]",
      gradientSecond:
        "radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 201, 0.30) 0%, rgba(51, 5, 32, 0.30) 100%)",
      ellipceImg: "/images/successRate-2/ellipceImg.webp",
      card: "/images/successRate-3/card.webp",
      roseR: "/images/successRate-3/rose-r.png",
      woman: "/images/successRate-3/woman.webp",
      borderClass: "border-gradient-rounded-3",
      accentBg: "bg-accent-gradient-3",
    },
    target: {
      mainImg: "/images/target-3/img1.webp",
      roseBack: "/images/target-3/rose-back.webp",
      roseL: "/images/target-3/rose-l.png",
      borderColor: "borderColor-3",
    },
    videoInstruction: {
      bg: "/images/videoInstruction-3/bg.webp",
      gradient: "bg-[#170111]",
      card: "/images/videoInstruction-3/card.png",
      roseL: "/images/videoInstruction-3/rose-l.png",
      roseR: "/images/videoInstruction-3/rose-r.png",
    },
    reviews: {
      heart: "/images/reviews/heart-3.webp",
      gradient:
        " radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 198, 0.50) 0%, rgba(51, 5, 27, 0.50) 100%)",
      slideBg: "bg-[#CB3C92]",
      quotes: "/icons/quotes-3.svg",
      play: "/icons/play-3.svg",
      prev: "/icons/prev-3.svg",
      prevClass: "w-[153px] object-[0_4px]",
      next: "/icons/next-3.svg",
    },
  },
  {
    id: "tamara",
    url: "/tamara",
    textColor: "txtColor3",
    menu: "/icons/menu3.svg",
    close: "/icons/close3.svg",
    menuGradient: "dark-to-light-3",
    menuHeart: "/images/heart3.webp",
    burgerBg: "burger-bg-3",
    txtGradient: "txt-gradient-3",
    lightGradient: "lightGradient-3",
    firstbg: "bgFirstAndSecondBlocks-third",
    banner: {
      womanPhoto: "/images/hero-4/hero.webp",
      womanClass: "top-[88px]",
      womanImg: "w-full",
      roseBack: "/images/hero-3/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#170111]  w-[662px] h-[832px]",
      roseL: "/images/hero-3/rose-l.png",
      roseR: "/images/hero-3/rose-r.png",
      bannerTxt: "Секретный ритуал",
      accentTxt: "Ввостанови любовь",
      lastTxt: "Научись правильно делать любовный ритуал",
    },
    txtSection: {
      img: "/images/txtSection/img-3.png",
      gradient: "bg-[#4A3945]",
    },
    about: {
      heart: "/images/about-3/heart.webp",
      roseL: "/images/about-3/rose-l.png",
      roseR: "/images/about-3/rose-r.png",
      itemClass: "borderColor-3 bg-dark-to-light-3",
    },
    successRate: {
      gradient: "bg-[#4A3945]",
      gradientSecond:
        "radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 201, 0.30) 0%, rgba(51, 5, 32, 0.30) 100%)",
      ellipceImg: "/images/successRate-2/ellipceImg.webp",
      card: "/images/successRate-3/card.webp",
      roseR: "/images/successRate-3/rose-r.png",
      woman: "/images/successRate-4/woman.webp",
      borderClass: "border-gradient-rounded-3",
      accentBg: "bg-accent-gradient-3",
    },
    target: {
      mainImg: "/images/target/img1.webp",
      roseBack: "/images/target/rose-back.webp",
      roseL: "/images/target-3/rose-l.png",
      borderColor: "borderColor-3",
    },
    videoInstruction: {
      bg: "/images/videoInstruction-3/bg.webp",
      gradient: "bg-[#170111]",
      card: "/images/videoInstruction-3/card.png",
      roseL: "/images/videoInstruction-3/rose-l.png",
      roseR: "/images/videoInstruction-3/rose-r.png",
    },
    reviews: {
      heart: "/images/reviews/heart-3.webp",
      gradient:
        " radial-gradient(50% 50% at 50% 50%, rgba(255, 39, 198, 0.50) 0%, rgba(51, 5, 27, 0.50) 100%)",
      slideBg: "bg-[#CB3C92]",
      quotes: "/icons/quotes-3.svg",
      play: "/icons/play-3.svg",
      prev: "/icons/prev-3.svg",
      prevClass: "w-[153px] object-[0_4px]",
      next: "/icons/next-3.svg",
    },
  },
];
