export const variantsData = [
  {
    id: "victoria",
    url: "/",
    textColor: "txtColor",
    menu: "/icons/menu.svg",
    close: "/icons/close.svg",
    menuGradient: "dark-to-light",
    menuHeart: "/icons/heart.svg",
    burgerBg: "burger-bg",
    txtGradient: "txt-gradient",
    lightGradient: "lightGradient",
    firstbg: "bgFirstAndSecondBlocks",
    banner: {
      womanPhoto: "/images/hero/hero.webp",
      womanClass: "top-[78px]",
      womanImg: "w-[299px]",
      roseBack: "/images/hero/rose-back.webp",
      roseBgClass: "object-[-97px_0]",
      bannerGradientClass: "top-[406px] bg-[#170101]  w-[521px] h-[783px]",
      roseL: "/images/hero/rose-l.webp",
      roseR: "/images/hero/rose-r.webp",
      bannerTxt: "Сила любви у тебя в руках",
      accentTxt: "Забери своё",
      lastTxt: "Пошаговый ритуал, который может всё изменить",
    },
    txtSection: {
      img: "/images/txtSection/img.png",
      gradient: "bg-[#470808]",
    },
    about: {
      heart: "/images/about/heart.webp",
      roseL: "/images/about/rose-l.png",
      roseR: "/images/about/rose-r.png",
      itemClass: "borederColor bg-dark-to-light",
    },
  },
  {
    id: "ayym-qunan",
    url: "/ayym-qunan",
    textColor: "txtColor2",
    menu: "/icons/menu2.svg",
    close: "/icons/close2.svg",
    menuGradient: "dark-to-light-2",
    menuHeart: "/images/heart2.webp",
    burgerBg: "burger-bg-2",
    txtGradient: "txt-gradient-2",
    lightGradient: "lightGradient-2",
    firstbg: "bgFirstAndSecondBlocks-second",
    banner: {
      womanPhoto: "/images/hero-2/hero.webp",
      womanClass: "top-[-1px]",
      womanImg: "w-full",
      roseBack: "/images/hero-2/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#010D17]  w-[662px] h-[832px]",
      roseL: "/images/hero-2/rose-l.png",
      roseR: "/images/hero-2/rose-r.png",
      bannerTxt: "Возвращение любимого",
      accentTxt: "Забери своё",
      lastTxt: "100% проверенная практика, которую используют мастера",
    },
    txtSection: {
      img: "/images/txtSection/img-2.png",
      gradient: "bg-[#39394A]",
    },
    about: {
      heart: "/images/about-2/heart.webp",
      roseL: "/images/about-2/rose-l.png",
      roseR: "/images/about-2/rose-r.png",
      itemClass: "borederColor-2 bg-dark-to-light",
    },
  },
  {
    id: "anastasia",
    url: "/anastasia",
    textColor: "txtColor3",
    menu: "/icons/menu3.svg",
    close: "/icons/close3.svg",
    menuGradient: "dark-to-light-3",
    menuHeart: "/icons/heart-3.svg",
    burgerBg: "burger-bg-3",
    txtGradient: "txt-gradient-3",
    lightGradient: "lightGradient-3",
    firstbg: "bgFirstAndSecondBlocks-third",
    banner: {
      womanPhoto: "/images/hero-3/hero.webp",
      womanClass: "top-[-1px]",
      womanImg: "w-full",
      roseBack: "/images/hero-3/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#170111]  w-[662px] h-[832px]",
      roseL: "/images/hero-3/rose-l.png",
      roseR: "/images/hero-3/rose-r.png",
      bannerTxt: "Научись притягивать",
      accentTxt: "Ты - наслаждение",
      lastTxt: "Курс для тех, кто хочет раскрыть свою природную магнетичность",
    },
    txtSection: {
      img: "/images/txtSection/img-3.png",
      gradient: "bg-[#4A3945]",
    },
    about: {
      heart: "/images/about-3/heart.webp",
      roseL: "/images/about-3/rose-l.png",
      roseR: "/images/about-3/rose-r.png",
      itemClass: "borederColor-3 bg-dark-to-light",
    },
  },
  {
    id: "tamara",
    url: "/tamara",
    textColor: "txtColor3",
    menu: "/icons/menu3.svg",
    close: "/icons/close3.svg",
    menuGradient: "dark-to-light-3",
    menuHeart: "/images/heart3.webp",
    burgerBg: "burger-bg-3",
    txtGradient: "txt-gradient-3",
    lightGradient: "lightGradient-3",
    firstbg: "bgFirstAndSecondBlocks-third",
    banner: {
      womanPhoto: "/images/hero-4/hero.webp",
      womanClass: "top-[88px]",
      womanImg: "w-full",
      roseBack: "/images/hero-3/rose-back.webp",
      bannerGradientClass: "top-[358px] bg-[#170111]  w-[662px] h-[832px]",
      roseL: "/images/hero-3/rose-l.png",
      roseR: "/images/hero-3/rose-r.png",
      bannerTxt: "Секретный ритуал",
      accentTxt: "Ввостанови любовь",
      lastTxt: "Научись правильно делать любовный ритуал",
    },
    txtSection: {
      img: "/images/txtSection/img-3.png",
      gradient: "bg-[#4A3945]",
    },
    about: {
      heart: "/images/about-3/heart.webp",
      roseL: "/images/about-3/rose-l.png",
      roseR: "/images/about-3/rose-r.png",
      itemClass: "borederColor bg-dark-to-light",
    },
  },
];
